import {proposalPhotos,proposalPackagePhotos} from './proposal-photos.js';
import {inspiration} from './inspiration.js';
import {packages as sweetPackages, addons as sweetAddons} from './catalog.js';
const makePackages=(rows,looks)=>Object.fromEntries(rows.map(([id,name,description])=>[id,{name,description,price:null,looks:looks.map(([title,description])=>[title,null,description])}]));
const extras=(rows)=>Object.fromEntries(rows.map(([id,name,description])=>[id,[name,null,description]]));
export const events={
 sweet16:{name:'Sweet Sixteen',title:'Your Sweet Sixteen, beautifully imagined.',intro:'A celebration as individual as you. Explore your package, choose a look, and bring every detail together.',palette:'Blush pink, champagne and ivory',packages:sweetPackages,addons:sweetAddons,defaultPackage:'sweet'},
 proposals:{name:'Proposals',title:'Set the scene for your yes.',intro:'From a private candlelit moment to a statement floral reveal, design a proposal that feels like your story.',palette:'Ivory, soft rose and champagne',packages:makePackages([
 ['moment','The Yes Moment','A compact proposal focal point with a freestanding backdrop and modest flowers; no dining setup.'],['candles','Candlelit Romance','A romantic proposal spot with a short aisle of enclosed LED candles and a floral focal point.'],['garden','Garden Promise','An intimate outdoor garden proposal with a floral arch and natural surroundings.'],['rooftop','Above the City','A refined rooftop proposal with a compact floral frame and city views.'],['dinner','Dinner for Two','One beautifully styled dining table for two, candlelight and a discreet floral backdrop.'],['signature','The Signature Yes','A statement floral proposal backdrop with a coordinated entrance pathway.'],['luxe','The Luxe Proposal','A lush premium floral reveal with layered lighting and an intimate seating area.'],['extra','The Extraordinaire Proposal','A fully coordinated private proposal setting with entrance, floral focal point and dinner for two.']
 ],[['Modern romance','Sculptural ivory forms, restrained roses and warm lighting.'],['Rose garden','Romantic rose arrangements in an intimate garden-inspired setting.'],['After dark','Deep red accents, warm enclosed candlelight and a refined evening atmosphere.']]),addons:extras([
 ['sign','Marry me sign','A clearly readable illuminated MARRY ME sign at the focal point'],['petals','Petal pathway','A neat rose-petal pathway leading to the proposal focal area'],['candles','Candle aisle','A line of enclosed LED candles along the approach'],['floral','Premium floral upgrade','Extra-full premium roses around the focal installation'],['table','Celebration table','One additional intimate celebration table for two'],['drape','Soft draping','Romantic soft draping framing the proposal'],['lounge','Couple’s lounge','One refined loveseat for the couple'],['balloon','Balloon styling','A restrained organic balloon arrangement at the backdrop']]),defaultPackage:'moment'},
 birthdays:{name:'Birthdays',title:'Another year. A whole new moment.',intro:'Milestone dinners, joyful garden parties and statement celebrations. Create a birthday that feels unmistakably yours.',palette:'Champagne, ivory and gold',packages:makePackages([
 ['photo','The Birthday Moment','A compact cake and photo backdrop with simple flowers.'],['party','The Party Edit','A styled birthday focal area and a small cake table.'],['garden','The Garden Birthday','An outdoor birthday lunch setting with coordinated guest tables and flowers.'],['lounge','The Birthday Lounge','A statement celebrant chair, birthday backdrop and coordinated floral accents.'],['dinner','The Birthday Dinner','A refined birthday dinner with styled guest tables and a cake focal point.'],['signature','The Signature Birthday','A statement birthday backdrop, cake table and coordinated guest-table decor.'],['luxe','The Luxe Birthday','An elevated milestone party with premium floral focal styling and guest tables.'],['extra','The Extraordinaire Birthday','A coordinated venue transformation with birthday stage, entrance, guest tables and dance floor.']
 ],[['Modern milestone','Contemporary architectural backdrop with clean lines and sophisticated metallic accents.'],['Colourful celebration','Joyful colour-blocked panels and playful table details; balloons only if selected.'],['Evening elegance','Moody lighting, refined florals and elegant dinner-party styling.']]),addons:extras([
 ['marquee','Birthday age marquee','Large illuminated numbers showing only the supplied birthday age; omit numbers if no age supplied'],['sign','Personalised name sign','A personalised birthday name sign using only a supplied name'],['balloon','Balloon styling','Organic balloon garland around the birthday backdrop'],['cloud','Cloud Nine ceiling','A floating ceiling balloon installation in the chosen palette'],['table','Extra styled table','One additional fully styled guest table'],['floral','Premium florals','Additional premium floral volume'],['lounge','Celebrant lounge','An additional celebrant sofa or statement chair'],['tablecloth','Draped tablecloths','Gathered draped cloths on the requested number of tables']]),defaultPackage:'party'},
 traditional:{name:'African Traditional Weddings',title:'Your heritage. Your love. Your celebration.',intro:'Design an African traditional wedding around your families, colours and chosen traditions. Tell us which cultural details belong in your celebration.',palette:'Emerald, coral and gold',packages:makePackages([
 ['stage','The Introduction','An intimate family introduction focal backdrop with paired couple seating and modest florals.'],['heritage','The Heritage Stage','A traditional wedding focal stage with paired couple seats and coordinated textured backdrop.'],['garden','The Garden Gathering','An outdoor traditional wedding reception with couple seating and coordinated family tables.'],['family','The Family Celebration','A couple stage and intimate family seating with elegant table decor.'],['reception','The Reception Edit','A traditional wedding reception with couple stage and coordinated guest tables.'],['signature','The Signature Tradition','A statement couple stage with coordinated entrance and family-table styling.'],['luxe','The Luxe Heritage','A grand traditional wedding stage with premium florals and richly styled guest tables.'],['extra','The Extraordinaire Tradition','A full traditional wedding reception transformation with couple stage, entrance, guest tables and dance floor.']
 ],[['Nigerian elegance','A contemporary Nigerian traditional wedding reception with paired couple seating, ivory and gold decor. Ask for the family’s specific heritage; do not invent ethnic motifs or ritual items.'],['Ghanaian celebration','A contemporary Ghanaian traditional wedding reception with paired couple seating, warm gold and rich colours. Use specific cloth patterns or cultural details only when requested by the family.'],['Contemporary heritage','A refined African wedding reception with soft florals, layered textures and paired seating. Keep cultural details specific to the family rather than mixing traditions.']]),addons:extras([
 ['sign','Couple’s name sign','A couple-name sign using only supplied names'],['entrance','Statement entrance','A coordinated welcome entrance framing the reception'],['table','Extra family table','One additional styled family table'],['floral','Premium florals','Additional lush floral arrangements around the stage'],['drape','Venue draping','Coordinated elegant venue draping'],['gifts','Presentation display','A styled empty presentation table; do not invent ceremonial objects or ritual items'],['lounge','Family lounge','An additional comfortable family lounge area'],['tablecloth','Draped tablecloths','Gathered cloths on the requested number of tables']]),defaultPackage:'heritage'},
 weddings:{name:'White Weddings',title:'The beginning of your forever.',intro:'From an intimate ceremony to a complete reception transformation, bring your wedding vision together in one considered design.',palette:'Ivory, white and champagne',packages:makePackages([
 ['ceremony','The Ceremony Moment','An intimate wedding ceremony arch and simple aisle, without reception tables.'],['vows','The Vow Edit','A coordinated ceremony backdrop, aisle flowers and guest ceremony chairs.'],['garden','The Garden Wedding','An outdoor garden ceremony with floral arch, guest chairs and a natural aisle.'],['sweetheart','The Sweetheart Setting','A refined reception sweetheart table for two and coordinated floral backdrop.'],['reception','The Reception Edit','Elegant reception tables and a coordinated sweetheart focal point.'],['signature','The Signature Wedding','A coordinated wedding reception with statement couple focal point, guest tables and entrance.'],['luxe','The Luxe Wedding','A premium wedding reception with full florals, candlelit guest tables and an elegant couple stage.'],['extra','The Extraordinaire Wedding','A complete wedding reception transformation with entrance, couple stage, guest tables and dance floor.']
 ],[['Timeless ivory','Classic ivory flowers, elegant proportions and softly glowing candlelight.'],['Modern sculptural','Contemporary sculptural floral forms, clean architecture and refined white-on-white styling.'],['Garden romance','Airy garden-inspired florals, natural greenery and soft romantic textures.']]),addons:extras([
 ['aisle','Floral aisle','A clearly defined aisle with coordinated floral arrangements'],['sign','Couple’s name sign','A personalised couple-name sign using supplied names only'],['table','Extra guest table','One additional coordinated wedding guest table'],['floral','Premium florals','Fuller premium flowers around the main focal area'],['drape','Venue draping','Soft romantic venue draping'],['candles','Candle styling','Additional enclosed LED candle arrangements'],['lounge','Couple’s lounge','An additional elegant loveseat for the couple'],['tablecloth','Draped tablecloths','Gathered cloths on the requested number of tables']]),defaultPackage:'ceremony'}
};
export const enquiryEmail='decorator-extraordinaire@outlook.com';

export const eventOrder=['sweet16','proposals','birthdays','weddings','traditional'];
const startingPrices={proposals:[595,850,1250,1450,1650,2250,3250,4750],birthdays:[595,850,1450,1650,2250,3250,4750,6950],weddings:[1250,1850,2450,1650,3950,5750,7950,10950],traditional:[1450,2250,2950,3450,4950,6750,8950,11950]};
const addonPrices={sign:175,petals:125,candles:225,floral:650,table:195,drape:650,lounge:650,balloon:450,marquee:325,cloud:425,tablecloth:85,entrance:850,gifts:275,aisle:650};
const tableScopes={birthdays:{garden:3,dinner:4,signature:6,luxe:8,extra:10},weddings:{reception:8,signature:10,luxe:12,extra:15},traditional:{garden:4,family:5,reception:8,signature:10,luxe:12,extra:15}};
for(const [id,prices] of Object.entries(startingPrices)){
 const event=events[id];
 Object.values(event.packages).forEach((pkg,index)=>{
 pkg.price=prices[index];
 pkg.looks.forEach((look,i)=>{look[1]=inspiration[id][i].src;look[3]=inspiration[id][i].source;});
 });
 for(const [packageId,count] of Object.entries(tableScopes[id]||{}))event.packages[packageId].description+=` Starting scope: styling for up to ${count} venue-supplied guest tables (up to ${count*8} guests).`;
 for(const [addonId,addon] of Object.entries(event.addons))addon[1]=addonPrices[addonId];
 event.hero=inspiration[id][0];
}
// Match the visible inspiration directions with the generation instructions.
events.proposals.hero=proposalPhotos[4];
events.proposals.gallery=proposalPhotos;
for(const [id,pkg] of Object.entries(events.proposals.packages)){
 pkg.looks=proposalPackagePhotos[id].map(i=>{
  const photo=proposalPhotos[i];
  return [photo.label,photo.src,photo.description+' Adapt the inspiration to the selected package scale and venue. Include lettering, petal pathways and extra decorations only if selected or part of the base package. No people or vendor marks in the generated concept.',null,photo.credit];
 });
}
for(const pkg of Object.values(events.birthdays.packages)){
 pkg.looks[0][0]='Birthday surprise';pkg.looks[0][2]='A sophisticated surprise birthday setting with a warm celebratory palette; balloon decorations only when selected.';
 pkg.looks[1][0]='Garden celebration';pkg.looks[1][2]='Fresh garden-inspired colours, cheerful accents and relaxed elegant styling.';
 pkg.looks[2][0]='Evening elegance';
}
for(const pkg of Object.values(events.weddings.packages)){
 pkg.looks[0][0]='Ivory floral romance';pkg.looks[1][0]='Elegant reception';pkg.looks[2][0]='Garden elegance';
}
