import {packages as sweetPackages, addons as sweetAddons} from './catalog.js';
const makePackages=(rows,looks)=>Object.fromEntries(rows.map(([id,name,description])=>[id,{name,description,price:null,looks:looks.map(([title,description])=>[title,null,description])}]));
const extras=(rows)=>Object.fromEntries(rows.map(([id,name,description])=>[id,[name,null,description]]));
export const events={
 sweet16:{name:'Sweet Sixteen',title:'Your Sweet Sixteen, beautifully imagined.',intro:'A celebration as individual as you. Explore your package, choose a look, and bring every detail together.',palette:'Blush pink, champagne and ivory',packages:sweetPackages,addons:sweetAddons,defaultPackage:'sweet'},
 proposals:{name:'Proposals',title:'Set the scene for your yes.',intro:'From a private candlelit moment to a statement floral reveal, design a proposal that feels like your story.',palette:'Ivory, soft rose and champagne',packages:makePackages([
 ['moment','The Yes Moment','A compact proposal focal point with a freestanding backdrop and modest flowers; no dining setup.'],['candles','Candlelit Romance','A romantic proposal spot with a short aisle of enclosed LED candles and a floral focal point.'],['garden','Garden Promise','An intimate outdoor garden proposal with a floral arch and natural surroundings.'],['rooftop','Above the City','A refined rooftop proposal with a compact floral frame and city views.'],['dinner','Dinner for Two','One beautifully styled dining table for two, candlelight and a discreet floral backdrop.'],['signature','The Signature Yes','A statement floral proposal backdrop with a coordinated entrance pathway.'],['luxe','The Luxe Proposal','A lush premium floral reveal with layered lighting and an intimate seating area.'],['extra','The Extraordinaire Proposal','A fully coordinated private proposal setting with entrance, floral focal point and dinner for two.']
 ],[['Modern romance','Sculptural ivory forms, restrained roses and warm lighting.'],['Rose garden','Romantic rose arrangements in an intimate garden-inspired setting.'],['After dark','Deep red accents, warm enclosed candlelight and a refined evening atmosphere.']]),addons:extras([
 ['sign','Marry me sign','A clearly readable illuminated MARRY ME sign at the focal point'],['petals','Petal pathway','A neat rose-petal pathway leading to the proposal focal area'],['candles','Candle aisle','A line of enclosed LED candles along the approach'],['floral','Premium floral upgrade','Extra-full premium roses around the focal installation'],['table','Celebration table','One additional intimate celebration table for two'],['drape','Soft draping','Romantic soft draping framing the proposal'],['lounge','Couple’s lounge','One refined loveseat for the couple'],['balloon','Balloon styling','A restrained organic balloon arrangement at the backdrop']]),defaultPackage:'moment'},
 birthdays:{name:'Birthdays',title:'Another year. A whole new moment.',intro:'Milestone dinners, joyful garden parties and statement celebrations. Create a birthday that feels unmistakably yours.',palette:'Champagne, ivory and gold',packages:makePackages([
 ['photo','The Birthday Moment','A compact cake and photo backdrop with simple flowers.'],['party','The Party Edit','A styled birthday focal area and a small cake table.'],['garden','The Garden Birthday','An outdoor birthday lunch setting with coordinated guest tables and flowers.'],['lounge','The Birthday Lounge','A statement celebrant chair, birthday backdrop and coordinated floral accents.'],['dinner','The Birthday Dinner','A refined birthday dinner with styled guest tables and a cake focal point.'],['signature','The Signature Birthday','A statement birthday backdrop, cake table and coordinated guest-table decor.'],['luxe','The Luxe Birthday','An elevated milestone party with premium floral focal styling and guest tables.'],['extra','The Extraordinaire Birthday','A coordinated venue transformation with birthday stage, entrance, guest tables and dance floor.']
 ],[['Modern milestone','Contemporary architectural backdrop with clean lines and sophisticated metallic accents.'],['Colourful celebration','Joyful colour-blocked panels and playful table details; balloons only if selected.'],['Evening elegance','Moody lighting, refined florals and elegant dinner-party styling.']]),addons:extras([
 ['marquee','Birthday age marquee','Large illuminated numbers showing only the supplied birthday age; omit numbers if no age supplied'],['sign','Personalised name sign','A personalised birthday name sign using only a supplied name'],['balloon','Balloon styling','Organic balloon garland around the birthday backdrop'],['cloud','Cloud Nine ceiling','A floating ceiling balloon installation in the chosen palette'],['table','Extra styled table','One additional fully styled guest table'],['floral','Premium florals','Additional premium floral volume'],['lounge','Celebrant lounge','An additional celebrant sofa or statement chair'],['tablecloth','Draped tablecloths','Gathered draped cloths on the requested number of tables']]),defaultPackage:'party'},
 traditional:{name:'Nigerian Traditional Weddings',title:'Your heritage. Your love. Your celebration.',intro:'Design a Nigerian traditional wedding around your families, colours and chosen traditions. Tell us which cultural details belong in your celebration.',palette:'Emerald, coral and gold',packages:makePackages([
 ['stage','The Introduction','An intimate family introduction focal backdrop with paired couple seating and modest florals.'],['heritage','The Heritage Stage','A traditional wedding focal stage with paired couple seats and coordinated textured backdrop.'],['garden','The Garden Gathering','An outdoor traditional wedding reception with couple seating and coordinated family tables.'],['family','The Family Celebration','A couple stage and intimate family seating with elegant table decor.'],['reception','The Reception Edit','A traditional wedding reception with couple stage and coordinated guest tables.'],['signature','The Signature Tradition','A statement couple stage with coordinated entrance and family-table styling.'],['luxe','The Luxe Heritage','A grand traditional wedding stage with premium florals and richly styled guest tables.'],['extra','The Extraordinaire Tradition','A full traditional wedding reception transformation with couple stage, entrance, guest tables and dance floor.']
 ],[['Contemporary heritage','Contemporary stage design with refined woven textures and rich colours; cultural symbols only as specified.'],['Royal colour','Deep jewel tones, polished gold accents and dignified paired couple seating.'],['Soft tradition','Ivory and warm neutral styling with restrained textures, soft florals and paired seating.']]),addons:extras([
 ['sign','Couple’s name sign','A couple-name sign using only supplied names'],['entrance','Statement entrance','A coordinated welcome entrance framing the reception'],['table','Extra family table','One additional styled family table'],['floral','Premium florals','Additional lush floral arrangements around the stage'],['drape','Venue draping','Coordinated elegant venue draping'],['gifts','Presentation display','A styled empty presentation table; do not invent ceremonial objects or ritual items'],['lounge','Family lounge','An additional comfortable family lounge area'],['tablecloth','Draped tablecloths','Gathered cloths on the requested number of tables']]),defaultPackage:'heritage'},
 weddings:{name:'White Weddings',title:'The beginning of your forever.',intro:'From an intimate ceremony to a complete reception transformation, bring your wedding vision together in one considered design.',palette:'Ivory, white and champagne',packages:makePackages([
 ['ceremony','The Ceremony Moment','An intimate wedding ceremony arch and simple aisle, without reception tables.'],['vows','The Vow Edit','A coordinated ceremony backdrop, aisle flowers and guest ceremony chairs.'],['garden','The Garden Wedding','An outdoor garden ceremony with floral arch, guest chairs and a natural aisle.'],['sweetheart','The Sweetheart Setting','A refined reception sweetheart table for two and coordinated floral backdrop.'],['reception','The Reception Edit','Elegant reception tables and a coordinated sweetheart focal point.'],['signature','The Signature Wedding','A coordinated wedding reception with statement couple focal point, guest tables and entrance.'],['luxe','The Luxe Wedding','A premium wedding reception with full florals, candlelit guest tables and an elegant couple stage.'],['extra','The Extraordinaire Wedding','A complete wedding reception transformation with entrance, couple stage, guest tables and dance floor.']
 ],[['Timeless ivory','Classic ivory flowers, elegant proportions and softly glowing candlelight.'],['Modern sculptural','Contemporary sculptural floral forms, clean architecture and refined white-on-white styling.'],['Garden romance','Airy garden-inspired florals, natural greenery and soft romantic textures.']]),addons:extras([
 ['aisle','Floral aisle','A clearly defined aisle with coordinated floral arrangements'],['sign','Couple’s name sign','A personalised couple-name sign using supplied names only'],['table','Extra guest table','One additional coordinated wedding guest table'],['floral','Premium florals','Fuller premium flowers around the main focal area'],['drape','Venue draping','Soft romantic venue draping'],['candles','Candle styling','Additional enclosed LED candle arrangements'],['lounge','Couple’s lounge','An additional elegant loveseat for the couple'],['tablecloth','Draped tablecloths','Gathered cloths on the requested number of tables']]),defaultPackage:'ceremony'}
};
export const enquiryEmail='decorator-extraordinaire@outlook.com';
